config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  scope module: :public do
  root to: "homes#top"
  get "homes/about"=>"homes#about", as: "about"
  get "search" => "searches#search"

  resources :songs do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
   member do
    get :favorites
   end
  end
  get "/user/check"=>"users#check"
  patch "/user/withdraw" => "users#withdraw"
  end

  namespace :admin do
  resources :songs, only: [:index, :show, :destroy]

  resources :genres, only: [:index, :create, :edit, :update]

  resources :users, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :songs, dependent: :destroy 
  validates :name, presence: true
  
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
     redirect_back(fallback_location: root_path)
    else
     @genre = Genre.new
     @genres = Genre.all
     render :index
    end
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  private

  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container mt-5">
   <div class="row mb-4">
        <div class="col-xs mx-auto">
          <h3 class="text-info font-weight-bold mt-5">ジャンル編集</h3>
            <%= form_with model: @genre, url:admin_genre_path, local:true do |f| %>
            <table class="table">
              <tr>
                <th>ジャンル名</th>
                <th><%= f.text_field :name %></th>
                <th><%= f.submit "変更を保存",class: "btn btn-success" %></th>
              </tr>
            </table>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container mt-5">
   <div class="row mb-4">
        <div class="col-xs mx-auto">
 <h3 class="text-info font-weight-bold">ジャンル一覧・追加</h3>
</div>
</div>
   <div class="row">
    <div class="col-xs mx-auto">
        <%= form_with model: @genre, url:admin_genres_path, local:true do |f| %>
        <table class="table table-borderless">
         <tr>
          <th>ジャンル名</th>
          <th><%= f.text_field :name %></th>
          <th><%= f.submit "新規登録",class: "btn btn-success" %></th>
         </tr>
          <% end %>
        </table>

        <table class="table">
         <thead class="thead-light">
          <tr>
           <th>ジャンル</th>
           <th></th>
          </tr>
         </thead>

         <tbody>
         <% @genres.each do |genre| %>
          <tr>
           <td><%= genre.name %></td>
           <th><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></th>
          </tr>
         </tbody>
         <% end %>
        </table>
    </div>
  </div>
</div>