config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  scope module: :public do
  root to: "homes#top"
  get "homes/about"=>"homes#about", as: "about"
  get "search" => "searches#search"

  resources :songs do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
   member do
    get :favorites
   end
  end
  get "/user/check"=>"users#check"
  patch "/user/withdraw" => "users#withdraw"
  end

  namespace :admin do
  resources :songs, only: [:index, :show, :destroy]

  resources :genres, only: [:index, :create, :edit, :update]

  resources :users, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :image       
  has_many :songs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :name, presence: true
  validates :name, length: { maximum: 10 }
  
  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
  
  def favorited?(user)
     favorites.where(user_id: user.id).exists?
  end
  
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "introduction", "is_withdrawal", "name", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
  
  def active_for_authentication?
    super && (is_withdrawal == false)
  end
  
  
  def user_status
    if is_withdrawal == true
      "退会"
    else
      "有効"
    end
  end
  
  GUEST_USER_EMAIL = "guest@example.com"
  
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'guestuser'
    end
  end
 
  def guest_user?
    email == GUEST_USER_EMAIL
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @songs = @user.songs.all
    @favorites = Favorite.where(user_id: @user.id).pluck(:song_id)
    @favorite_songs = Song.find(@favorites)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    @user.songs.destroy_all
    @user.comments.destroy_all
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :is_withdrawal, :image)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_favorites.html.erb
  <div class="row mt-3">
    <% favorite_songs.each do |song| %>
    <div class="col-md-4 mb-3">
     <div class="card border-info h-100">
      <p class="ml-2 mt-2"><%= song.created_at.strftime('%Y/%m/%d %H:%M') %></p>
     <div class="card-img-top ">
     <%= link_to user_path(song.user.id) do %>
      <%= image_tag song.user.get_image, size: "50×50" %>
     <% end %>
     <p class="font-weight-bold ml-2">
      <i class="fa-solid fa-user"></i>
      <%= song.user.name %>
     </p>
     </div>
     <p class="card-title ml-2 font-weight-bold">
      <i class="fa-solid fa-record-vinyl"></i>
      <%= truncate(song.title, length: 7) %>
      <i class="fa-solid fa-tag", style="padding-left:10px;"></i>
      <%= song.genre.name %>
     </p>
     <div class="card-text", style="padding-left:10px;"><%= simple_format(truncate(song.body, length: 28)) %></div>
      <table class="ml-3 mb-3">
       <tr>
        <td id="favorite_buttons_<%=song.id%>"><%= render "public/favorites/favorites", song: song %></td>
        <td id="comment_count"><%= render "public/comments/count", song: song %></td>
        <td>
         <%= link_to admin_song_path(song.id) do %>
          <i class="fa-solid fa-circle-info"></i>詳細
         <% end %>
        </td>
       </tr>
      </table>
     </div>
    </div>
    <% end %>
  </div>

app/views/admin/users/_mylist.html.erb
 <div class="row mt-3">
  <% songs.each do |song| %>
   <div class="col-md-4 mb-3">
     <div class="card border-info h-100">
      <p class="ml-2 mt-2"><%= song.created_at.strftime('%Y/%m/%d %H:%M') %></p>
     <div class="card-img-top ">
      <%= image_tag song.user.get_image, size: "50×50" %>
     <p class="font-weight-bold ml-2">
      <i class="fa-solid fa-user"></i>
      <%= song.user.name %>
     </p>
     </div>
     <p class="card-title ml-2 font-weight-bold">
      <i class="fa-solid fa-record-vinyl"></i>
      <%= truncate(song.title, length: 7) %>
      <i class="fa-solid fa-tag", style="padding-left:10px;"></i>
      <%= song.genre.name %>
     </p>
     <div class="card-text", style="padding-left:10px;"><%= simple_format(truncate(song.body, length: 28)) %></div>
      <table class="ml-3 mb-3">
       <tr>
        <td id="favorite_buttons_<%=song.id%>"><%= render "public/favorites/favorites", song: song %></td>
        <td id="comment_count"><%= render "public/comments/count", song: song %></td>
        <td>
         <%= link_to admin_song_path(song.id) do %>
          <i class="fa-solid fa-circle-info"></i>詳細
         <% end %>
        </td>
       </tr>
      </table>
     </div>
    </div>
    <% end %>
  </div>

app/views/admin/users/index.html.erb
<div class="container">
 <div class="row mt-5">
  <div class='col'>
   <h3 class="text-info font-weight-bold">会員一覧</h3>
  </div>
 </div>
   <div class="row mt-3">
        <% @users.each do |user| %>
    <div class="col-md-3 mb-3">
     <div class="card border-info h-100">
     <div class="card-img-top"><%= image_tag user.get_image, size: "50×50" %></div>
      <div class="card-body">
       <h5 class="card-title mb-1 font-weight-bold"><%= user.name %></h5>
       <h6 class="card-subtitle mb-3">
          <i class="fa-solid fa-envelope"></i>
          <%= user.email %>
       </h6>
       <p class="card-text"><%= truncate(user.introduction, length: 8) %></p>
      <table>
       <tr>
        <td>
         <i class="fa-solid fa-person"></i>
         <% if user.is_withdrawal == true %>
          <span style="color:darkgray;"><%= "退会" %></strong>
         <% else %>
          <strong style="color:orange;"><%= "有効" %></strong>
         <% end %>
        </td>
        <td style="padding-left:20px">
         <%= link_to admin_user_path(user.id) do %>
         <i class="fa-solid fa-circle-info"></i>詳細
         <% end %>
        </td>
       </tr>
      </table>
      </div>
     </div>
    </div>
    <% end %>
   </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class='row mt-5'>
    <div class='col-md-4'>
     <table class='table table-borderless'>
      <tr>
       <th class="text-center">ユーザー画像</th>
       <td><%= image_tag @user.get_image, size:'100x100' %></td>
      </tr>
      <tr>
	   <th class="text-center">ユーザー名</th>
	   <th><%= @user.name %></th>
      </tr>
      <tr>
	   <th class="text-center">メールアドレス</th>
	   <th><%= @user.email %></th>
      </tr>
      <tr>
	   <th class="text-center">自己紹介</th>
	   <th><%= @user.introduction %></th>
      </tr>
      <tr>
	   <th class="text-center">ステータス</th>
	   <th>
	    <% if @user.is_withdrawal == true %>
         <span style="color:darkgray;"><%= "退会" %></strong>
        <% else %>
         <strong style="color:orange;"><%= "有効" %></strong>
        <% end %>
      </th>
      </tr>
      <tr>
	   <th class="text-center">作成日時</th>
	   <th><%= @user.created_at.strftime('%Y/%m/%d %H:%M') %></th>
      </tr>      
     </table>
     
     <div class="mx-auto", style="padding-left:80px">
      <%= link_to 'ユーザーを削除する', admin_user_path(@user), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %>
     </div>
    </div>



<div class='col-md-7 offset-md-1 mt-2'>
      <div class="tabs d-flex justify-content-between align-items-center">
        <ul class="nav nav-tabs">
          <li class="nav-item">
           <a class="nav-link active" data-toggle="tab" href="#mylist">自分の投稿</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#favorites">いいね</a>
          </li>
        </ul>
      </div>

     <div class="tab-content">
       <div id="mylist" class="tab-pane fade show active">
        <%= render 'mylist', songs: @songs %>
       </div>
     <div id="favorites" class="tab-pane fade">
       <%= render 'favorites', favorite_songs: @favorite_songs %>
      </div>
    </div>
</div>
</div>
</div>