config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


  scope module: :public do
  root to: "homes#top"
  get "homes/about"=>"homes#about", as: "about"
  get "search" => "searches#search"

  resources :songs do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
   member do
    get :favorites
   end
  end
  get "/user/check"=>"users#check"
  patch "/user/withdraw" => "users#withdraw"
  end

  namespace :admin do
  resources :songs, only: [:index, :show, :destroy]

  resources :genres, only: [:index, :create, :edit, :update]

  resources :users, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
  <div class='container' style="padding-top:20px">
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight 2023 Takumi Tsujimura</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark p-4" style="background-color: #deb887;">
    <div class="container-md">

      <a class="navbar-brand" href="/"><%= image_tag 'Progressing.png' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>

          <li class='mt-3 font-weight-bold' style="color: #fff; padding-right:60px">
            ようこそ、<%= current_user.name %>さん！
          </li>
          <li class="btn btn-outline-light btn-sm ml-3">
            <%= link_to root_path,class: 'nav-link text-light' do %> Home
            <% end %>
          </li>
          <li class="btn btn-outline-light btn-sm ml-3">
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %> マイページ
            <% end %>
          </li>
          <li class="btn btn-outline-light btn-sm ml-3">
            <%=  link_to songs_path,class: 'nav-link text-light' do %> 投稿一覧
            <% end %>
          </li>
          <li class="btn btn-outline-light btn-sm ml-3">
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %> ログアウト
            <% end %>
          </li>

        <% elsif admin_signed_in? %>

          <li class="btn btn-outline-light btn-sm ml-3">
            <%=  link_to admin_users_path ,class: 'nav-link text-light' do %> 会員一覧
            <% end %>
          </li>
          <li class="btn btn-outline-light btn-sm ml-3">
            <%=  link_to admin_songs_path ,class: 'nav-link text-light' do %> 投稿一覧
            <% end %>
          </li>
          <li class="btn btn-outline-light btn-sm ml-3">
            <%=  link_to admin_genres_path ,class: 'nav-link text-light' do %> ジャンル一覧
            <% end %>
          </li>
          <li class="btn btn-outline-light btn-sm ml-3">
            <%=  link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-light' do %> ログアウト
            <% end %>
          </li>

        <% else %>

          <li class="btn btn-outline-light btn-sm ml-3">
            <%= link_to root_path,class: 'nav-link text-light' do %> Home
            <% end %>
          </li>
          <li class="btn btn-outline-light btn-sm ml-3">
            <%= link_to users_guest_sign_in_path, method: :post,class: 'nav-link text-light' do %> ゲストログイン
            <% end %>
          </li>
          <li class="btn btn-outline-light btn-sm ml-3">
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %> 新規登録
            <% end %>
          </li>
          <li class="btn btn-outline-light btn-sm ml-3">
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %> ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Progressing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/cd2e65d323.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="wrapper", style="background-color: #FFFAF0;">
    <main>
      <%= render 'layouts/header' %>
      <%= yield %>
    </main>
    <div style="padding-top:40px">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>